basic_lti_app/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^$', 'basic_lti_app.views.index', name='index'),
    url(r'^index.html$', 'basic_lti_app.views.index', name='index2'),
    url(r'^lti_launch$', 'basic_lti_app.views.lti_launch', name='lti_launch'),
    url(r'^main$', 'basic_lti_app.views.main', name='main'),
    url(r'^tool_config$', 'basic_lti_app.views.tool_config', name='tool_config'),
)

maps/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^$', 'maps.views.index', name='index'),
    url(r'^lti_launch$', 'maps.views.lti_launch', name='lti_launch'),
    url(r'^main$', 'maps.views.main', name='main'),
    url(r'^tool_config$', 'maps.views.tool_config', name='tool_config'),

    )

maptool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'maptool.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^lti_tools/basic_lti_app/', include('basic_lti_app.urls', namespace="basic_lti_app")),
    url(r'^lti_tools/maptoolapp/', include('maptoolapp.urls', namespace="maptoolapp")),
    url(r'^lti_tools/maps/', include('maps.urls', namespace="maps")),
    url(r'^lti_tools/auth_error/', 'maptool.views.lti_auth_error', name='lti_auth_error'),
)

basic_lti_app/views.py
from django.shortcuts import (render, redirect)
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from ims_lti_py.tool_config import ToolConfig
from django.http import HttpResponse

# Create your views here.

TOOL_NAME = "basic_lti_app"

@require_http_methods(['GET'])
def index(request):
    """
    Show the index file
    """
    return render(request, 'basic_lti_app/index.html')

@login_required()
@require_http_methods(['POST'])
def lti_launch(request):
    """
    This method is here to build the LTI_LAUNCH dictionary containing all
    the LTI parameters and place it into the session. This is nessesary as we 
    need to access these parameters throughout the application and they are only 
    available the first time the application loads.
    """
    if request.user.is_authenticated():
        return redirect('basic_lti_app:main')
    else:
        return render(request, 'basic_lti_app/error.html', {'message': 'Error: user is not authenticated!'})

@login_required()
@require_http_methods(['GET'])
def main(request):
    """
    The main method dipslay the default view which is the map_view.
    """

    lti_params_dict = request.session.get('LTI_LAUNCH', {})

    return render(request, 'basic_lti_app/lti_view.html', {'request': request, 'lti_params_dict': lti_params_dict})

@require_http_methods(['GET'])
def tool_config(request):
    """
    This produces a Canvas specific XML config that can be used to
    add this tool to the Canvas LMS
    """
    if request.is_secure():
        host = 'https://' + request.get_host()
    else:
        host = 'http://' + request.get_host()

    url = host + reverse('basic_lti_app:lti_launch')

    lti_tool_config = ToolConfig(
        title='Basic LTI App',
        launch_url=url,
        secure_launch_url=url,
    )
    account_nav_params = {
        'enabled': 'true',
        # optionally, supply a different URL for the link:
        # 'url': 'http://library.harvard.edu',
        'text': 'basic lti app',
    }
    lti_tool_config.set_ext_param('canvas.instructure.com', 'privacy_level', 'public')
    lti_tool_config.set_ext_param('canvas.instructure.com', 'course_navigation', account_nav_params)
    lti_tool_config.description = 'This LTI app shows all the LTI parameters'

    resp = HttpResponse(lti_tool_config.to_xml(), content_type='text/xml', status=200)
    return resp

basic_lti_app/templates/basic_lti_app/error.html
<html>
<head>
    <title>Error</title>
</head>
<body>

<h1> ERROR </h1>

<p>{{ message }}</p>



</body>
</html>

basic_lti_app/templates/basic_lti_app/index.html
<!DOCTYPE html>
<html>
<head>
<title>Basic LTI App</title>
</head>
<body>

<h1>Basic LTI App</h1>

<p>
    This tool appears in the course navigation area in Canvas, and can be used by course administrators to add a link to student locations for the course.
</p>
<p>
	To configure this tool in Canvas, use the XML configuration here: <a href="{% url 'basic_lti_app:tool_config' %}">XML Configuration</a>
</p>

</body>
</html>

basic_lti_app/templates/basic_lti_app/lti_view.html
<!DOCTYPE html>
<html>
<head>
<title>Basic LTI App</title>
</head>
<style>
    th { background: lightgray}
    tr:nth-child(even) {background: #FFF}
    tr:nth-child(odd) {background: lightblue}
    #lti-table {margin-left: 5px; }
</style>
<body>

<h1>LTI Params</h1>

<table id="lti-table" width="80%" cellpadding="2px" cellspacing="2px">
    <thead>
    <tr><th>Num</th><th>LTI Param Name</th><th>Value</th></tr>
    </thead>
    <tbody>
    {% for k,v in lti_params_dict.iteritems %}
	    <tr><td>{{forloop.counter}}</td><td>{{ k }}</td><td>{{ v }}</td></tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>