maps/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^$', 'maps.views.index', name='index'),
    url(r'^lti_launch$', 'maps.views.lti_launch', name='lti_launch'),
    url(r'^main$', 'maps.views.main', name='main'),
    url(r'^tool_config$', 'maps.views.tool_config', name='tool_config'),

    )

maptool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'maptool.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^lti_tools/basic_lti_app/', include('basic_lti_app.urls', namespace="basic_lti_app")),
    url(r'^lti_tools/maptoolapp/', include('maptoolapp.urls', namespace="maptoolapp")),
    url(r'^lti_tools/maps/', include('maps.urls', namespace="maps")),
    url(r'^lti_tools/auth_error/', 'maptool.views.lti_auth_error', name='lti_auth_error'),
)

maptoolapp/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^$', 'maptoolapp.views.index', name='index'),
    url(r'^lti_launch$', 'maptoolapp.views.lti_launch', name='lti_launch'),
    url(r'^main$', 'maptoolapp.views.main', name='main'),
    url(r'^table_view$', 'maptoolapp.views.table_view', name='table_view'),
    url(r'^markers_class_xml$', 'maptoolapp.views.markers_class_xml', name='markers_class_xml'),
    url(r'^addoreditlocation$', 'maptoolapp.views.addoreditlocation', name='addlocation'),
    url(r'^tool_config$', 'maptoolapp.views.tool_config', name='tool_config'),
    url(r'^add_location$', 'maptoolapp.views.add_location', name='add_location'),
    url(r'^toolinstanceconfig$', 'maptoolapp.views.toolinstanceconfig', name='toolinstanceconfig'),
    url(r'^deleteview$', 'maptoolapp.views.deleteview', name='deleteview'),
    url(r'^displaymaps/(\d+)/$', 'maptoolapp.views.displaymaps', name='displaymaps'),
    url(r'^mapsview$', 'maptoolapp.views.mapsview', name='mapsview'),

    )

maps/models.py
from django.db import models

# Create your models here.

maptoolapp/models.py
from django.db import models


# Create your models here.


class Locations(models.Model):
    itemgroup = models.ForeignKey('ItemGroup')
    locality = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    generated_longitude = models.CharField(max_length=50)
    generated_latitude = models.CharField(max_length=50)
    method = models.CharField(max_length=10)
    datetime = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user_id = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    info = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    latitude = models.CharField(max_length=50)
    longitude = models.CharField(max_length=50)
    mapurl = models.CharField(max_length=200)

class Urls(models.Model):
    itemgroup = models.ForeignKey('ItemGroup')
    url_1 = models.CharField(max_length=250)
    generated_longitude_1 = models.CharField(max_length=50)
    generated_latitude_1 = models.CharField(max_length=50)
    zoom_1 = models.CharField(max_length=50)
    description_1 = models.CharField(max_length=250)
    url_2 = models.CharField(max_length=250)
    generated_longitude_2 = models.CharField(max_length=50)
    generated_latitude_2 = models.CharField(max_length=50)
    zoom_2 = models.CharField(max_length=50)
    description_2 = models.CharField(max_length=250)
    url_3 = models.CharField(max_length=250)
    generated_longitude_3 = models.CharField(max_length=50)
    generated_latitude_3 = models.CharField(max_length=50)
    zoom_3 = models.CharField(max_length=50)
    description_3 = models.CharField(max_length=250)

class ItemGroup(models.Model):
    context_id = models.CharField(max_length=50)
    resource_link_id = models.CharField(max_length=50)
    custom_canvas_course_id = models.CharField(max_length=50)
    item_name = models.CharField(max_length=50)
    item_description = models.CharField(max_length=500)

maps/views.py
from django.shortcuts import render, redirect
from maps.utils import (validaterequiredltiparams,
                        getparamfromsession)
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from ims_lti_py.tool_config import ToolConfig

# Create your views here.

@require_http_methods(['GET'])
def tool_config(request):
    """
    This produces a Canvas specific XML config that can be used to
    add this tool to the Canvas LMS
    """
    if request.is_secure():
        host = 'https://' + request.get_host()
    else:
        host = 'http://' + request.get_host()

    url = host + reverse('maps:lti_launch')

    lti_tool_config = ToolConfig(
        title='Maps',
        launch_url=url,
        secure_launch_url=url,
    )
    account_nav_params = {
        'enabled': 'true',
        # optionally, supply a different URL for the link:
        # 'url': 'http://library.harvard.edu',
        'text': 'Maps',
    }
    lti_tool_config.set_ext_param('canvas.instructure.com', 'privacy_level', 'public')
    lti_tool_config.set_ext_param('canvas.instructure.com', 'course_navigation', account_nav_params)
    lti_tool_config.description = 'This LTI tool facilitates the gathering pins for many similar locations on a map.'

    resp = HttpResponse(lti_tool_config.to_xml(), content_type='text/xml', status=200)
    return resp


@require_http_methods(['GET'])
def index(request):
    """
    Show the index file
    """
    return render(request, 'maps/main.html')

@login_required()
@require_http_methods(['POST'])
def lti_launch(request):
    """
    This method is here to build the LTI_LAUNCH dictionary containing all
    the LTI parameters and place it into the session. This is necessary as we
    need to access these parameters throughout the application and they are only
    available the first time the application loads.
    """
    if request.user.is_authenticated():
        if validaterequiredltiparams(request):
            return redirect('maps:main')
        else:
            return render(request, 'maps/error.html', {'message': 'Error: The LTI parameter '
                                                                  'lis_course_offering_sourcedid is '
                                                                  'required by this LTI tool.'})
    else:
        return render(request, 'maps/error.html', {'message': 'Error: user is not authenticated!'})


@login_required()
@require_http_methods(['GET'])
def main(request):

    admin = False
    user_type = getparamfromsession(request, 'roles')
    custom_canvas_course_id = getparamfromsession(request, 'custom_canvas_course_id')

    if "Instructor" in user_type:
        admin = True

    return render(request, 'maps/main.html', {'request': request,
                                              'user_is_admin' : admin,
                                              'course_id': custom_canvas_course_id,})

maptoolapp/views.py
from django.shortcuts import render, redirect, render_to_response
from django.views.decorators.http import require_http_methods
from ims_lti_py.tool_config import ToolConfig
from django.conf import settings
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from maptoolapp.forms import LocationForm, ItemGroupForm, UrlForm
from maptoolapp.utils import (validaterequiredltiparams)
import datetime
from django import forms
from maptoolapp.utils import getlatlongandzoom
from maptoolapp.utils import getparamfromsession
import urllib
import urllib2
import json
from models import Locations, Urls, ItemGroup

import logging
logger = logging.getLogger(__name__)


@require_http_methods(['GET'])
def index(request):
    """
    Show the index file
    """
    return render(request, 'maptoolapp/index.html')

@login_required()
@require_http_methods(['POST'])
def lti_launch(request):
    """
    This method is here to build the LTI_LAUNCH dictionary containing all
    the LTI parameters and place it into the session. This is necessary as we
    need to access these parameters throughout the application and they are only 
    available the first time the application loads.
    """
    if request.user.is_authenticated():
        if validaterequiredltiparams(request):
            return redirect('maptoolapp:main')
        else:
            return render(request, 'maptoolapp/error.html', {'message': 'Error: The LTI parameter '
                                                                        'lis_course_offering_sourcedid is '
                                                                        'required by this LTI tool.'})
    else:
        return render(request, 'maptoolapp/error.html', {'message': 'Error: user is not authenticated!'})

@login_required()
@require_http_methods(['GET'])
def main(request):
    """
    The main method display the default view which is the instance_selection view.
    """
    user_type = getparamfromsession(request, 'roles')
    custom_canvas_course_id = getparamfromsession(request, 'custom_canvas_course_id')

    # Check to make sure that both all itemgroups have a corresponding url have been submitted
    itemgroup_ids = ItemGroup.objects.all().values('id')
    for itemgroup in itemgroup_ids:
        check_itemgroup = itemgroup.get('id')
        check_url = Urls.objects.filter(itemgroup=check_itemgroup)
        if not check_url.exists():
            ItemGroup.objects.get(id=check_itemgroup).delete()

    data = ItemGroup.objects.filter(custom_canvas_course_id=custom_canvas_course_id)

    # If tool not configured and instructor logs in
    if ("Instructor" in user_type) and (data.count() == 0):
        itemgroupform = ItemGroupForm
        return render(request, 'maptoolapp/tool_instance_config_page1.html', {'request': request, 'itemgroupform':
            itemgroupform})

    # If any other user arrives at an unconfigured tool
    elif ("Instructor" not in user_type) and (data.count() == 0):
        return render(request, 'maptoolapp/error.html', {'message': 'Error: The course instructor must configure this '
                                                                    'tool before it can be accessed.'})

    # Where all users should go once the tool is configured
    else:
        return render(request, 'maptoolapp/itemgroup_instance_selection.html', {'request': request, 'data': data})

@login_required()
@require_http_methods(['GET'])
def displaymaps(request, data):
    """
    Set the id of the desired view in session and render map_view.html
    """
    request.session['itemgroup_session'] = data
    urls = Urls.objects.get(itemgroup=data)
    itemgroup = ItemGroup.objects.filter(id = data)
    key = settings.MAP_TOOL_APP.get('google_map_api_v3_key')
    user_id = getparamfromsession(request, 'user_id')
    mypoints = Locations.objects.filter(user_id=user_id, itemgroup=data)
    return render(request, 'maptoolapp/map_view.html', {'request': request, 'api_key': key, 'urls': urls, 'itemgroup':
        itemgroup, 'mypoints': mypoints})

@login_required()
@require_http_methods(['GET'])
def mapsview(request):
    """
    Render map_view.html from any page once a view is saved in session
    """
    user_id = getparamfromsession(request, 'user_id')
    itemgroup_session = request.session.get('itemgroup_session')
    urls = Urls.objects.get(itemgroup=itemgroup_session)
    itemgroup = ItemGroup.objects.filter(id = itemgroup_session)
    key = settings.MAP_TOOL_APP.get('google_map_api_v3_key')
    mypoints = Locations.objects.filter(user_id=user_id, itemgroup=itemgroup_session)
    return render(request, 'maptoolapp/map_view.html', {'request': request, 'api_key': key, 'urls': urls, 'itemgroup':
        itemgroup, 'mypoints': mypoints})

@login_required()
@require_http_methods(['GET'])
def add_location(request):
    """
    Displays the add location view which allows users to enter locations
    and descriptions for display on the Google map.
    """
    resource_link_id = getparamfromsession(request, 'resource_link_id')
    user_id = getparamfromsession(request, 'user_id')
    if not resource_link_id or not user_id:
        return render(request, 'maptoolapp/error.html', {'message': 'Unable to retrieve params from session. '
                                                                    'You might want to try reloading the tool.'})
    locationform = LocationForm
    return render(request, 'maptoolapp/add_location.html', {'request': request, 'locationform': locationform})

@login_required()
@require_http_methods(['POST'])
def deleteview(request):
    """
    Allows an instructor to delete a view from the tool.
    """
    theclass = request.POST.get('class')
    data = request.POST.get('id')
    if theclass == 'deleteRow':
        ItemGroup.objects.filter(id=data).delete()
        return HttpResponse('')
    else:
        Locations.objects.filter(id=data).delete()
        itemgroup_session = request.session.get('itemgroup_session')
        urls = Urls.objects.get(itemgroup=itemgroup_session)
        itemgroup = ItemGroup.objects.filter(id = itemgroup_session)
        key = settings.MAP_TOOL_APP.get('google_map_api_v3_key')
        user_id = getparamfromsession(request, 'user_id')
        mypoints = Locations.objects.filter(user_id=user_id, itemgroup=itemgroup_session)
        return render(request, 'maptoolapp/map_view.html', {'request': request, 'api_key': key, 'urls': urls,
                                                            'itemgroup': itemgroup, 'mypoints': mypoints})

@login_required()
def addoreditlocation(request):
    """
    The action method for the user_edit_view form.
    """
    enter_user_id = getparamfromsession(request, 'user_id')
    lis_person_name_family = getparamfromsession(request, 'lis_person_name_family')
    lis_person_name_given = getparamfromsession(request, 'lis_person_name_given')

    locationform = LocationForm(first_name=lis_person_name_given, last_name=lis_person_name_family,
                                user_id=enter_user_id, data=request.POST)

    if locationform.is_valid():
        user_id = getparamfromsession(request, 'user_id')
        itemgroup_session = request.session.get('itemgroup_session')
        mypoints = Locations.objects.filter(user_id=user_id, itemgroup=itemgroup_session)
        urls = Urls.objects.get(itemgroup=itemgroup_session)
        itemgroup = ItemGroup.objects.filter(id = itemgroup_session)
        theform = locationform.save(commit=False)
        theform.itemgroup = ItemGroup.objects.get(id=itemgroup_session)
        theform.first_name = lis_person_name_given
        theform.last_name = lis_person_name_family
        theform.user_id = enter_user_id
        theform.datetime = datetime.datetime.now()
        theform.save()
        key = settings.MAP_TOOL_APP.get('google_map_api_v3_key')
        return render(request, 'maptoolapp/map_view.html', {'request': request, 'api_key': key, 'urls': urls,
                                                            'itemgroup': itemgroup, 'mypoints': mypoints})
    else:
        return render(request, 'maptoolapp/add_location.html', {'request': request, 'locationform': locationform})

@login_required()
def toolinstanceconfig(request):
    """
    The action method for the configuring a new instance of the tool.
    """
    context_id = getparamfromsession(request, 'context_id')
    custom_canvas_course_id = getparamfromsession(request, 'custom_canvas_course_id')
    resource_link_id = getparamfromsession(request, 'resource_link_id')

    itemgroupform = ItemGroupForm(context_id=context_id, custom_canvas_course_id=custom_canvas_course_id,
                                  resource_link_id=resource_link_id, data=request.POST)
    urlform = UrlForm(data=request.POST)
    if request.POST:
        if itemgroupform.is_valid():
            theitemform = itemgroupform.save(commit=False)
            theitemform.context_id = context_id
            theitemform.custom_canvas_course_id = custom_canvas_course_id
            theitemform.resource_link_id = resource_link_id
            theitemform.save()
            request.session['itemgroup_session'] = theitemform.id
            render_url_form = UrlForm
            return render(request, 'maptoolapp/tool_instance_config_page2.html', {'request': request,
                                                                                  'urlform': render_url_form})
        elif urlform.is_valid():
            itemgroupform = ItemGroup.objects.get(id=request.session.get('itemgroup_session'))
            theurlform = urlform.save(commit=False)
            url_1 = theurlform.url_1
            url_2 = theurlform.url_2
            url_3 = theurlform.url_3

            if url_1:
                try:
                    urllib.urlopen(url_1)
                    latlong_1, zoom_1 = getlatlongandzoom(url_1)

maptoolapp/templates/maptoolapp/_header.html
{% load staticfiles %}

<p class="text-box">
    {% if 'Instructor' in request.session.LTI_LAUNCH.roles %}
        <a href="{% url 'maptoolapp:toolinstanceconfig' %}">Add or Edit a Map View</a>&#160;|&#160;
    {% endif %}
        <a href="{% url 'maptoolapp:add_location' %}">Add Location</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:mapsview' %}">View Map</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:table_view' %}">View Table</a>
</p>

maptoolapp/templates/maptoolapp/_map_view_style.html
{% load staticfiles %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <style>
        .map-style {
            width: 80%;
            height: 400px;
            display: inline-block;
        }
        .my-points {
            display: inline-block;
            position: absolute;
        }
        .map-container {
            margin: 20px;
        }
        .point-title {
            font-weight: bold;
            font-size: 1em;
            margin-left: 20px;
        }
        div#data_url { display: none; }
    </style>
{% endblock %}

maptoolapp/templates/maptoolapp/add_location.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
<title>Add Locations</title>

{% block stylsheet %}
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
  <style type="text/css">
  #add_user_form { margin-left: 10px; margin-top: 10px; max-width: 80%;}
  .location-box { border: thin solid lightgrey; margin: 10px 10px; padding: 10px 10px;}
  .text-box { margin: 10px 10px; padding: 10px 10px;}
  legend { border-bottom: 0; }
  </style>
 {% endblock %}
</head>
<body>

{% block content %}

<div id="add_user_form">

<p class="text-box">
        <a href="{% url 'maptoolapp:toolinstanceconfig' %}">Add or Edit a Map View</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:add_location' %}">Add Location</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:mapsview' %}">View Map</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:table_view' %}">View Table</a>
</p>

{% crispy locationform %}

</div>
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/error.html
<html>
<head>
    <title>Error</title>
</head>
<body>

<h1> ERROR </h1>

<p class="help-block">{{ message }}</p>

<a href="{% url 'maptoolapp:main' %}">Back to the main page.</a>

</body>
</html>

maptoolapp/templates/maptoolapp/index.html
<!DOCTYPE html>
<html>
<head>
    <title>LTI Map Tool</title>
</head>

<body>
<h1>LTI Map Tool</h1>

<p>
    This tool appears in the course navigation area in Canvas, and can be used by course administrators to add a link to student locations for the course.
</p>
<p>
    To configure this tool in Canvas, use the XML configuration here: <a href="{% url 'maptoolapp:tool_config' %}">XML Configuration</a>
</p>

</body>
</html>

maptoolapp/templates/maptoolapp/itemgroup_instance_selection.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Select Tool Instance</title>
    {% block stylsheet %}
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    {% endblock %}
</head>

<body>
{% block content %}
    <div class="text-center">
        <h3>Select a tool instance to view:</h3><br>
        {% for rec in data %}
            <a href="{% url 'maptoolapp:displaymaps' rec.id %}"><i class="fa fa-map-marker fa-2x"></i> {{rec.item_name }}</a><br><br>
        {% endfor %}
</div>
{% endblock %}

{% block javascript %}
    <script src="{% static "js/jquery-1.10.2.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/maptool.js" %}"></script>
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/map_view.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>LTI Map App</title>

    {%  include 'maptoolapp/_map_view_style.html' %}
    {% block javascript %}
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&sensor=false"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/maptool.js" %}"></script>
    {% endblock %}
</head>

<body>
{% block content %}
    <div id="content-div" class="row-fluid">
    {% include 'maptoolapp/_header.html' %}
    {% for rec in itemgroup %}
        <div class="text-center"><h3>{{ rec.item_name }}</h3><h4>{{ rec.item_description }}</h4></div>
    {% endfor %}

    {% if urls.url_1 %}
        <div class="map-container">
            <h3>{{ urls.description_1 }}</h3>
            <div id="map_canvas_1" data-lat="{{ urls.generated_latitude_1 }}" data-long="{{ urls.generated_longitude_1 }}" data-zoom="{{ urls.zoom_1 }}" data-item_group_id="{{ urls.itemgroup_id }}" class="map-style">&#160;</div>
            <div class="my-points">
                <p class="point-title">My Points</p>
                <ul>
                    {% for point in mypoints %}
                        <li class="delete-point" data-id="{{ point.id }}">{{ point.title }} <a href="#"><i class="fa fa-trash"></i></a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
    {% if urls.url_2 %}
        <div class="map-container">
            <h3>{{ urls.description_2 }}</h3>
            <div id="map_canvas_2" data-lat="{{ urls.generated_latitude_2 }}" data-long="{{ urls.generated_longitude_2 }}" data-zoom="{{ urls.zoom_2 }}" data-item_group_id="{{ urls.itemgroup_id }}" class="map-style">&#160;</div>
        </div>
    {% endif %}
    {% if urls.url_3 %}
        <div class="map-container">
            <h3>{{ urls.description_3 }}</h3>
            <div id="map_canvas_3" data-lat="{{ urls.generated_latitude_3 }}" data-long="{{ urls.generated_longitude_3 }}" data-zoom="{{ urls.zoom_3 }}" data-item_group_id="{{ urls.itemgroup_id }}" class="map-style">&#160;</div>
        </div>
        <table>
            {% for key, val in lti_launch %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ val }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    <div id="data_url">{% url 'maptoolapp:markers_class_xml' %}</div>
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/table_view.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Table View</title>
    {% block stylsheet %}
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
    {% endblock %}
</head>

<body>
{% block content %}
    {% include 'maptoolapp/_header.html' %}
        <table class="table table-striped table-bordered table-condensed">
            <caption>Pinned Locations</caption>
            <thead>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Location Name</th>
                <th>Location Information</th>
                <th>Google Map URL</th>
            </thead>
            <tbody>
            {% for rec in data %}
                <tr>
                    <td> {{ rec.first_name }} </td>
                    <td> {{ rec.last_name }} </td>
                    <td> {{ rec.title }} </td>
                    <td> {{ rec.info }} </td>
                    <td><a href="http://maps.google.com/?q={{ rec.generated_latitude }},{{ rec.generated_longitude }}" target="_blank">Location of {{ rec.title }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/tool_instance_config_page1.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Tool Configuration</title>
    {% block stylsheet %}
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <style type="text/css">
            .text-box { margin: 10px 10px; padding: 10px 10px;}
            legend { border-bottom: 0; }
        </style>
    {% endblock %}
</head>

<body>
{% block content %}
    {% if data and count != "0" %}
        {% include 'maptoolapp/_header.html' %}
        <div class="text-center">
            <h3>Delete an existing view here:</h3>
            {%  for rec in data %}
                <div class="deleteRow" data-id="{{ rec.id }}">
                    {{ rec.item_name }} <a href="#" ><i class="fa fa-trash-o fa-2x"></i></a><br><br>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% crispy itemgroupform %}

{% endblock %}

{% block javascript %}
    <script src="{% static "js/jquery-1.10.2.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/maptool.js" %}"></script>
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/tool_instance_config_page2.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Tool Configuration</title>
    {% block stylsheet %}
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
        <style type="text/css">
            legend { border-bottom: 0; }
        </style>
    {% endblock %}
</head>

<body>
{% block content %}
    {% crispy urlform %}
{% endblock %}
</body>
</html>

maptoolapp/templates/maptoolapp/user_edit_view.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
<title>LTI Student Locations Edit Form</title>

{% block stylsheet %}
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" media="screen"/>
  <style type="text/css">
  #add_user_form { margin-left: 10px; margin-top: 10px; max-width: 80%;}
  .location-box { border: thin solid lightgrey; margin: 10px 10px; padding: 10px 10px;}
  .text-box { margin: 10px 10px; padding: 10px 10px;}
  legend { border-bottom: 0; }
  </style>
 {% endblock %}
</head>
<body>

{% block content %}

<div id="add_user_form">

      <p class="text-box">
        <a href="{% url 'maptoolapp:user_edit_view' %}">Edit My Information</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:main' %}">View Map</a>&#160;|&#160;
        <a href="{% url 'maptoolapp:table_view' %}">View Table</a>
      </p>

{% crispy form %}

</div>
{% endblock %}
</body>
</html>